//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion3_Gestion_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int id_Paciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> id_medico { get; set; }
    
        public virtual Medico Medico { get; set; }
    }
}
